from app.chatbot.training_utils import train_intent_model

# Datos de entrenamiento ampliados exponencialmente
training_data = [
    # Preguntas teóricas (muchas variaciones)
    ("¿Qué es Agrobot?", "theoretical"), ("¿Q es Agrobot?", "theoretical"), ("¿Que es Agrobot?", "theoretical"),
    ("¿k es agrobot?", "theoretical"), ("¿Qué significa Agrobot?", "theoretical"), ("¿Agrobot q es?", "theoretical"),
    ("¿Cómo funciona Agrobot?", "theoretical"), ("¿Para qué sirve Agrobot?", "theoretical"),
    ("¿Qué hace Agrobot?", "theoretical"), ("¿Agrobot qué hace?", "theoretical"),
    ("¿De dónde saca la información Agrobot?", "theoretical"),
    ("¿Agrobot puede recomendarme un cultivo específico según mi suelo?", "theoretical"),
    ("¿Cómo responde Agrobot si no sabe algo?", "theoretical"), ("¿Agrobot puede equivocarse?", "theoretical"),
    ("¿Qué es la agroecología?", "theoretical"), ("¿Q es agroecologia?", "theoretical"),
    ("¿Que es agroecología?", "theoretical"), ("¿Qué es agroecologia?", "theoretical"),
    ("¿k es agroecologia?", "theoretical"), ("¿Qué significa agroecología?", "theoretical"),
    ("¿Cómo funciona agroecología?", "theoretical"), ("¿Para qué sirve agroecología?", "theoretical"),
    ("¿Por qué es importante la agroecología para pequeños productores?", "theoretical"),
    ("¿Qué es agricultura sostenible?", "theoretical"), ("¿Q es agricultura sostenible?", "theoretical"),
    ("¿Agricultura sostenible q es?", "theoretical"), ("¿Que es agricutura sostenible?", "theoretical"),
    ("¿k es agricutura sostenible?", "theoretical"), ("¿Qué es agricutura sostenible?", "theoretical"),
    ("¿Cómo funciona agricultura sostenible?", "theoretical"),
    ("¿Beneficios agricultura sostenible?", "theoretical"), ("¿Qué hace sostenible agricultura?", "theoretical"),
    ("¿Qué diferencia hay entre agricultura sostenible y agroecología?", "theoretical"),
    ("¿Cómo controlo plagas orgánicas?", "theoretical"), ("¿Q hago plagas orgánicas?", "theoretical"),
    ("¿Cómo manejar plagas sin químicos?", "theoretical"), ("¿Como controlar plagas sin quimicos?", "theoretical"),
    ("¿k hago con plagas organicas?", "theoretical"), ("¿Qué hago si hay plagas resistentes a pesticidas orgánicos?", "theoretical"),
    ("¿Qué es rotación cultivos?", "theoretical"), ("¿Q es rotacion de cultivos?", "theoretical"),
    ("¿Que es rotacion de cultivos?", "theoretical"), ("¿k es rotacion cultivos?", "theoretical"),
    ("¿Para qué sirve rotación cultivos?", "theoretical"), ("¿Qué pasaría si no uso rotación de cultivos?", "theoretical"),
    ("¿Me conviene rotar papa con maíz o con tomate?", "theoretical"),
    ("¿Qué es agricultura precisión?", "theoretical"), ("¿Q es agricultura de precision?", "theoretical"),
    ("¿Que es agricultura prevision?", "theoretical"), ("¿k es agricultura de prevision?", "theoretical"),
    ("¿Para qué sirve la agricutura prevision?", "theoretical"), ("¿Cómo usa tecnología agricultura precisión?", "theoretical"),
    ("¿Cómo accedo financiamiento agrícola?", "theoretical"), ("¿Q hago financiamiento agricola?", "theoretical"),
    ("¿Dónde consigo apoyo agrícola?", "theoretical"),
    ("¿Qué es agricultura regenerativa?", "theoretical"), ("¿Q es regenerativa agricultura?", "theoretical"),
    ("¿Cómo mejora suelo regenerativa?", "theoretical"),
    ("¿Qué es agricultura urbana?", "theoretical"), ("¿Q es urbana agricultura?", "theoretical"),
    ("¿Cómo funciona urbana agricultura?", "theoretical"),
    ("¿Se puede hacer agricultura urbana en espacios pequeños?", "theoretical"),
    ("¿Qué es permacultura?", "theoretical"), ("¿Q es permacultura?", "theoretical"),
    ("¿Beneficios permacultura?", "theoretical"),
    ("¿Qué ventajas tiene la permacultura sobre agricultura convencional?", "theoretical"),
    ("¿Qué son cultivos transgénicos?", "theoretical"), ("¿Q son transgenicos?", "theoretical"),
    ("¿Cómo se hacen transgénicos?", "theoretical"),
    ("¿Qué es manejo integrado plagas?", "theoretical"), ("¿Q es mip?", "theoretical"),
    ("¿Cómo aplica mip?", "theoretical"),
    ("¿Qué es lixiviación nutrientes?", "theoretical"), ("¿Q es lixiviacion?", "theoretical"),
    ("¿Por qué pasa lixiviación?", "theoretical"),
    ("¿Qué es agricultura biodinámica?", "theoretical"), ("¿Q es biodinamica?", "theoretical"),
    ("¿Cómo funciona biodinámica?", "theoretical"),
    ("¿Qué es fertilidad suelo?", "theoretical"), ("¿Q es fertilidad?", "theoretical"),
    ("¿Cómo mejora fertilidad suelo?", "theoretical"),
    ("¿Qué es monocultivo?", "theoretical"), ("¿Q es monocultivo?", "theoretical"),
    ("¿Desventajas monocultivo?", "theoretical"),
    ("¿Qué es agricultura conservación?", "theoretical"), ("¿Q es conservacion?", "theoretical"),
    ("¿Cómo protege conservación suelo?", "theoretical"),
    ("¿Qué son biofertilizantes?", "theoretical"), ("¿Q son biofertilizantes?", "theoretical"),
    ("¿Cómo usan biofertilizantes?", "theoretical"),
    ("¿Puedo mezclar biofertilizantes y abonos orgánicos?", "theoretical"),
    ("¿Qué es pH suelo?", "theoretical"), ("¿Q es pH?", "theoretical"),
    ("¿Por qué importa pH suelo?", "theoretical"),
    ("¿Qué impacto tiene el pH del suelo en el rendimiento del tomate?", "theoretical"),
    ("¿Qué es erosión suelo?", "theoretical"), ("¿Q es erosion?", "theoretical"),
    ("¿Cómo evitar erosión suelo?", "theoretical"),
    ("¿Cómo siembro en invernadero?", "theoretical"), ("¿Q siembro invernadero?", "theoretical"),
    ("¿Como sembrar en invernadero?", "theoretical"), ("¿k siembro en invernadero?", "theoretical"),
    ("¿Técnicas siembra invernadero?", "theoretical"),
    ("¿Qué es siembra hidropónica?", "theoretical"), ("¿Q es hidropónica?", "theoretical"),
    ("¿Que es hidoponica?", "theoretical"), ("¿k es hidropónica?", "theoretical"),
    ("¿Qué es la hidoponica?", "theoretical"), ("¿Cómo funciona hidropónica?", "theoretical"),
    ("¿Qué son abonos orgánicos?", "theoretical"), ("¿Q son abonos orgánicos?", "theoretical"),
    ("¿Que son abonos organicos?", "theoretical"), ("¿k son abonos organicos?", "theoretical"),
    ("¿Cómo hago abonos orgánicos?", "theoretical"),
    ("¿Qué es compostaje?", "theoretical"), ("¿Q es compostaje?", "theoretical"),
    ("¿Que es compostaje?", "theoretical"), ("¿k es compostaje?", "theoretical"),
    ("¿Beneficios compostaje?", "theoretical"),
    ("¿Cómo afecta el clima lluvioso a la producción de papa?", "weather_sowing_advice"),
    
    # Preguntas de clima (muchas más ciudades y variaciones)
    ("¿Cuál es clima Bogotá?", "weather"), ("¿Q clima Bogotá?", "weather"), ("¿Cómo está tiempo Bogotá?", "weather"),
    ("¿Clima Medellín?", "weather"), ("¿Q tiempo Medellín?", "weather"), ("¿Está lloviendo Medellín?", "weather"),
    ("¿Clima Cali?", "weather"), ("¿Cómo está clima Cali?", "weather"), ("¿Tiempo hoy Cali?", "weather"),
    ("¿Clima Barranquilla?", "weather"), ("¿Q hace Barranquilla?", "weather"), ("¿Soleado Barranquilla?", "weather"),
    ("¿Clima Cartagena?", "weather"), ("¿Tiempo Cartagena?", "weather"), ("¿Lluvia Cartagena?", "weather"),
    ("¿Clima Pereira?", "weather"), ("¿Q clima Pereira?", "weather"), ("¿Cómo está Pereira?", "weather"),
    ("¿Clima Bucaramanga?", "weather"), ("¿Tiempo Bucaramanga?", "weather"), ("¿Soleado Bucaramanga?", "weather"),
    ("¿Clima Manizales?", "weather"), ("¿Q tiempo Manizales?", "weather"), ("¿Lluvioso Manizales?", "weather"),
    ("¿Clima Cúcuta?", "weather"), ("¿Cómo está Cúcuta?", "weather"), ("¿Tiempo Cúcuta?", "weather"),
    ("¿Clima mañana Bogotá?", "weather_forecast"), ("¿Q hará Bogotá?", "weather_forecast"),
    ("¿Pronóstico Bogotá?", "weather_forecast"), ("¿Clima mañana Medellín?", "weather_forecast"),
    ("¿Tiempo mañana Medellín?", "weather_forecast"), ("¿Soleado mañana Medellín?", "weather_forecast"),
    ("¿Clima fin semana Cali?", "weather_forecast"), ("¿Q tiempo fin semana Cali?", "weather_forecast"),
    ("¿Lluvia fin semana Cali?", "weather_forecast"),
    ("¿Clima semana próxima Barranquilla?", "weather_forecast"),
    ("¿Pronóstico Barranquilla?", "weather_forecast"), ("¿Tiempo semana Barranquilla?", "weather_forecast"),
    ("¿Clima para sembrar Bogotá?", "weather_sowing_advice"), ("¿Q clima sembrar Bogotá?", "weather_sowing_advice"),
    ("¿Bueno sembrar Bogotá?", "weather_sowing_advice"), ("¿Bueno sembar clima frio?", "weather_sowing_advice"),
    ("¿Clima sembrar Medellín?", "weather_sowing_advice"), ("¿Tiempo sembrar Medellín?", "weather_sowing_advice"),
    ("¿Adecuado sembrar Medellín?", "weather_sowing_advice"),
    ("¿Clima cultivo Cali?", "weather_sowing_advice"), ("¿Q clima cultivo Cali?", "weather_sowing_advice"),
    ("¿Bueno cultivar Cali?", "weather_sowing_advice"),
    ("¿Cuál es el clima ideal para sembrar cacao y en qué departamento es mejor?", "weather_sowing_advice"),
    
    # Preguntas de ubicación (más departamentos)
    ("¿Dónde estoy?", "current_location"), ("¿Q ciudad estoy?", "current_location"), ("¿Mi ubicación?", "current_location"),
    ("¿Estoy Antioquia?", "current_location"), ("¿Q departamento Antioquia?", "current_location"), ("¿En Antioquia?", "current_location"),
    ("¿Estoy Cundinamarca?", "current_location"), ("¿Q ciudad Cundinamarca?", "current_location"), ("¿En Cundinamarca?", "current_location"),
    ("¿Estoy Valle del Cauca?", "current_location"), ("¿Q departamento Valle?", "current_location"), ("¿En Valle?", "current_location"),
    ("¿Estoy Tolima?", "current_location"), ("¿Q ciudad Tolima?", "current_location"), ("¿En Tolima?", "current_location"),
    ("¿Estoy Santander?", "current_location"), ("¿Q departamento Santander?", "current_location"), ("¿En Santander?", "current_location"),
    ("¿Estoy Nariño?", "current_location"), ("¿Q ciudad Nariño?", "current_location"), ("¿En Nariño?", "current_location"),
    ("¿Estoy Huila?", "current_location"), ("¿Q departamento Huila?", "current_location"), ("¿En Huila?", "current_location"),
    ("¿Estoy Boyacá?", "current_location"), ("¿Q ciudad Boyacá?", "current_location"), ("¿En Boyacá?", "current_location"),
    
    # Preguntas de recomendación de cultivos (más cultivos y departamentos)
    ("¿Q cultivos región?", "recommendation"), ("¿Cultivos para zona?", "recommendation"),
    ("¿Qué siembro región?", "recommendation"), ("¿Que cultivos para mi regn?", "recommendation"),
    ("¿k cultivos para mi regn?", "recommendation"), ("¿k cultivos para mi regin?", "recommendation"),
    ("¿Cultivos departamento?", "recommendation"), ("¿Q plantar área?", "recommendation"),
    ("¿Mejores cultivos zona?", "recommendation"), ("¿Cuál es el mejor cultvio para mi zona?", "recommendation"),
    ("¿Qué puedo plantar si tengo poca lluvia?", "recommendation"),
    ("¿Q debo sembrar si mi suelo es ácido?", "recommendation"),
    ("¿Qué recomiendas para suelos arenosos en Huila?", "recommendation"),
    ("¿Por qué recomiendas el cultivo de café en Antioquia?", "recommendation"),
    ("¿Cultivo Antioquia?", "location_based_recommendation"), ("¿Q siembro Antioquia?", "location_based_recommendation"),
    ("¿Que sembrar en Antioquia?", "location_based_recommendation"), ("¿k siembro Antioquia?", "location_based_recommendation"),
    ("¿Mejor cultivo Antioquia?", "location_based_recommendation"),
    ("¿Cultivo Cundinamarca?", "location_based_recommendation"), ("¿Q siembro Cundinamarca?", "location_based_recommendation"),
    ("¿Que cultivos sembrar en Cundinamarca?", "location_based_recommendation"), ("¿k siembro Cundinamarca?", "location_based_recommendation"),
    ("¿Ideal Cundinamarca?", "location_based_recommendation"),
    ("¿Cuáles cultivos aguantan heladas en Cundinamarca?", "location_based_recommendation"),
    ("¿Cultivo Valle del Cauca?", "location_based_recommendation"), ("¿Q siembro Valle?", "location_based_recommendation"),
    ("¿Mejor Valle?", "location_based_recommendation"),
    ("¿Cultivo Tolima?", "location_based_recommendation"), ("¿Q plantar Tolima?", "location_based_recommendation"),
    ("¿Ideal Tolima?", "location_based_recommendation"),
    ("¿Cultivo Santander?", "location_based_recommendation"), ("¿Q siembro Santander?", "location_based_recommendation"),
    ("¿Que cultivos sembrar en Santander?", "location_based_recommendation"), ("¿k siembro Santander?", "location_based_recommendation"),
    ("¿Mejor Santander?", "location_based_recommendation"),
    ("¿Cultivo Nariño?", "location_based_recommendation"), ("¿Q plantar Nariño?", "location_based_recommendation"),
    ("¿Ideal Nariño?", "location_based_recommendation"),
    ("¿Cultivo Huila?", "location_based_recommendation"), ("¿Q siembro Huila?", "location_based_recommendation"),
    ("¿Mejor Huila?", "location_based_recommendation"),
    ("¿Cultivo Boyacá?", "location_based_recommendation"), ("¿Q plantar Boyacá?", "location_based_recommendation"),
    ("¿Ideal Boyacá?", "location_based_recommendation"),
    ("¿Qué puedo sembrar en Boyacá durante temporada seca?", "location_based_recommendation"),
    ("¿Dónde puedo cultiva maiz en caldas?", "location_based_recommendation"),
    ("¿Qué cultivos recomiendas Santander?", "recommended_crops"), ("¿Mejores cultivos Santander?", "recommended_crops"),
    ("¿Qué sembrar en Santander?", "recommended_crops"), ("¿Que cultivos recomiendas en Santander?", "recommended_crops"),
    ("¿k cultivos recomiendas Santander?", "recommended_crops"),
    ("¿Qué cultivos recomiendas Antioquia?", "recommended_crops"), ("¿Mejores cultivos Antioquia?", "recommended_crops"),
    ("¿Qué sembrar en Antioquia?", "recommended_crops"),
    ("¿Qué cultivos recomiendas Valle?", "recommended_crops"), ("¿Mejores cultivos Valle?", "recommended_crops"),
    ("¿Qué sembrar en Valle?", "recommended_crops"),
    ("¿Qué cultivos recomiendas Tolima?", "recommended_crops"), ("¿Mejores cultivos Tolima?", "recommended_crops"),
    ("¿Qué sembrar en Tolima?", "recommended_crops"),
    ("¿Qué cultivos recomiendas Huila?", "recommended_crops"), ("¿Mejores cultivos Huila?", "recommended_crops"),
    ("¿Qué sembrar en Huila?", "recommended_crops"),
    
    # Preguntas de rentabilidad (más cultivos)
    ("¿Cultivo rentable Antioquia?", "crop_profitability"), ("¿Q gana Antioquia?", "crop_profitability"),
    ("¿Que cultvio rentable Antioquia?", "crop_profitability"), ("¿k gana Antioquia?", "crop_profitability"),
    ("¿Mejor rentabilidad Antioquia?", "crop_profitability"),
    ("¿Cultivo rentable Cundinamarca?", "crop_profitability"), ("¿Q gana Cundinamarca?", "crop_profitability"),
    ("¿Mejor rentabilidad Cundinamarca?", "crop_profitability"),
    ("¿Cultivo rentable Valle?", "crop_profitability"), ("¿Q gana Valle?", "crop_profitability"),
    ("¿Mejor rentabilidad Valle?", "crop_profitability"),
    ("¿Rentable maíz donde?", "crop_profitability"), ("¿Q gana maíz?", "crop_profitability"),
    ("¿Que lugar rentable maiz?", "crop_profitability"), ("¿k gana maiz?", "crop_profitability"),
    ("¿Mejor maíz?", "crop_profitability"),
    ("¿Rentable papa donde?", "crop_profitability"), ("¿Q gana papa?", "crop_profitability"),
    ("¿Mejor papa?", "crop_profitability"),
    ("¿Rentable café donde?", "crop_profitability"), ("¿Q gana café?", "crop_profitability"),
    ("¿Mejor café?", "crop_profitability"),
    ("¿Rentable tomate donde?", "crop_profitability"), ("¿Q gana tomate?", "crop_profitability"),
    ("¿Mejor tomate?", "crop_profitability"),
    ("¿Rentable arroz donde?", "crop_profitability"), ("¿Q gana arroz?", "crop_profitability"),
    ("¿Mejor arroz?", "crop_profitability"),
    ("¿Rentable guayaba donde?", "crop_profitability"), ("¿Q gana guayaba?", "crop_profitability"),
    ("¿En que departamento es mas rentable guayaba?", "crop_profitability"), ("¿k gana guayaba?", "crop_profitability"),
    ("¿Mejor guayaba?", "crop_profitability"),
    ("¿Rentable plátano donde?", "crop_profitability"), ("¿Q gana plátano?", "crop_profitability"),
    ("¿Mejor plátano?", "crop_profitability"),
    ("¿Rentable cacao donde?", "crop_profitability"), ("¿Q gana cacao?", "crop_profitability"),
    ("¿Mejor cacao?", "crop_profitability"),
    ("¿Rentable yuca donde?", "crop_profitability"), ("¿Q gana yuca?", "crop_profitability"),
    ("¿Mejor yuca?", "crop_profitability"),
    ("¿Rentable caña azúcar donde?", "crop_profitability"), ("¿Q gana caña?", "crop_profitability"),
    ("¿Mejor caña?", "crop_profitability"),
    ("¿Conviene más sembrar maíz o arroz en Santander?", "crop_profitability"),
    ("¿Es más rentable maiz o yuca?", "crop_profitability"), ("¿Que es mas rentable maiz o yuca?", "crop_profitability"),
    ("¿k es mas rentable maiz o yuca?", "crop_profitability"),
    ("¿Es más rentable sembrar maíz o yuca en clima cálido?", "crop_profitability"),
    ("¿Qué cultivo me rinde más si sólo tengo 1 hectárea en Tolima?", "crop_profitability"),
    ("¿Qué cultivos rentables requieren poca agua?", "crop_profitability"),
    
    # Preguntas de producción (más cultivos)
    ("¿Donde producen menos maíz?", "crop_production"), ("¿Q menos maíz?", "crop_production"),
    ("¿En que departamento se produce menos maiz?", "crop_production"), ("¿k menos maiz?", "crop_production"),
    ("¿Menos maíz departamento?", "crop_production"),
    ("¿Donde producen más café?", "crop_production"), ("¿Q más café?", "crop_production"),
    ("¿Que departamento produce mas cafe?", "crop_production"), ("¿k mas cafe?", "crop_production"),
    ("¿Más café departamento?", "crop_production"),
    ("¿Producción tomate Cundinamarca?", "crop_production"), ("¿Q tomate Cundinamarca?", "crop_production"),
    ("¿Cuanta produccion tomate Cundinamarca?", "crop_production"), ("¿k tomate Cundinamarca?", "crop_production"),
    ("¿Tomate en Cundinamarca?", "crop_production"),
    ("¿Producción arroz Antioquia?", "crop_production"), ("¿Q arroz Antioquia?", "crop_production"),
    ("¿Arroz en Antioquia?", "crop_production"),
    ("¿Producción papa Valle?", "crop_production"), ("¿Q papa Valle?", "crop_production"),
    ("¿Papa en Valle?", "crop_production"),
    ("¿Producción guayaba Tolima?", "crop_production"), ("¿Q guayaba Tolima?", "crop_production"),
    ("¿Guayaba en Tolima?", "crop_production"),
    ("¿Producción plátano Santander?", "crop_production"), ("¿Q plátano Santander?", "crop_production"),
    ("¿Plátano en Santander?", "crop_production"),
    ("¿Producción cacao Nariño?", "crop_production"), ("¿Q cacao Nariño?", "crop_production"),
    ("¿Cacao en Nariño?", "crop_production"),
    ("¿Producción yuca Huila?", "crop_production"), ("¿Q yuca Huila?", "crop_production"),
    ("¿Yuca en Huila?", "crop_production"),
    ("¿Producción caña azúcar Boyacá?", "crop_production"), ("¿Q caña Boyacá?", "crop_production"),
    ("¿Caña en Boyacá?", "crop_production"),
    ("¿Qué departamento produce más arroz y es rentable?", "crop_production"),
    ("¿Cuánto maíz Manizales 2020?", "production_query"), ("¿Producción maíz Manizales 2020?", "production_query"),
    ("¿Que produjo maíz Manizales 2020?", "production_query"), ("¿k maiz Manizales 2020?", "production_query"),
    ("¿Cuánto café Caldas 2019?", "production_query"), ("¿Producción café Caldas 2019?", "production_query"),
    ("¿Que produjo café Caldas 2019?", "production_query"),
    ("¿Cuánto tomate Bogotá 2018?", "production_query"), ("¿Producción tomate Bogotá 2018?", "production_query"),
    ("¿Que produjo tomate Bogotá 2018?", "production_query"),
    ("¿Cuánto arroz Santander 2021?", "production_query"), ("¿Producción arroz Santander 2021?", "production_query"),
    ("¿Que produjo arroz Santander 2021?", "production_query"),
    ("¿Cuánto papa Boyacá 2022?", "production_query"), ("¿Producción papa Boyacá 2022?", "production_query"),
    ("¿Que produjo papa Boyacá 2022?", "production_query"),
    ("¿Tienes datos recientes de producción de papa en Boyacá?", "production_query"),
    ("¿Dónde encuentro cifras oficiales de cultivo de cacao?", "production_query"),
    ("¿Los datos de producción de arroz en Santander están actualizados?", "production_query"),
    
    # Preguntas de tiempo de siembra (más cultivos)
    ("¿Cuando siembro maíz?", "crop_timing"), ("¿Q mes maíz?", "crop_timing"), ("¿Mejor maíz?", "crop_timing"),
    ("¿Cundo siembro maiz?", "crop_timing"),
    ("¿Cuando siembro papa?", "crop_timing"), ("¿Q mes papa?", "crop_timing"), ("¿Mejor papa?", "crop_timing"),
    ("¿Cundo siembro papa?", "crop_timing"),
    ("¿Cuando siembro café?", "crop_timing"), ("¿Q mes café?", "crop_timing"), ("¿Mejor café?", "crop_timing"),
    ("¿Cundo siembro cafe?", "crop_timing"),
    ("¿Cuándo es mejor sembrar café si este año hay El Niño?", "crop_timing"),
    ("¿Cuando siembro tomate?", "crop_timing"), ("¿Q mes tomate?", "crop_timing"), ("¿Mejor tomate?", "crop_timing"),
    ("¿Cundo siembro tomate?", "crop_timing"),
    ("¿Cuando siembro arroz?", "crop_timing"), ("¿Q mes arroz?", "crop_timing"), ("¿Mejor arroz?", "crop_timing"),
    ("¿Cundo siembro arroz?", "crop_timing"),
    ("¿Cuando siembro guayaba?", "crop_timing"), ("¿Q mes guayaba?", "crop_timing"), ("¿Mejor guayaba?", "crop_timing"),
    ("¿Cundo siembro guayaba?", "crop_timing"),
    ("¿Cuando siembro plátano?", "crop_timing"), ("¿Q mes plátano?", "crop_timing"), ("¿Mejor plátano?", "crop_timing"),
    ("¿Cundo siembro platano?", "crop_timing"),
    ("¿Cuando siembro cacao?", "crop_timing"), ("¿Q mes cacao?", "crop_timing"), ("¿Mejor cacao?", "crop_timing"),
    ("¿Cundo siembro cacao?", "crop_timing"),
    ("¿Cuando siembro yuca?", "crop_timing"), ("¿Q mes yuca?", "crop_timing"), ("¿Mejor yuca?", "crop_timing"),
    ("¿Cundo siembro yuca?", "crop_timing"),
    ("¿Cuando siembro caña azúcar?", "crop_timing"), ("¿Q mes caña?", "crop_timing"), ("¿Mejor caña?", "crop_timing"),
    ("¿Cundo siembro caña azucar?", "crop_timing"),
    
    # Preguntas de riego (más variaciones)
    ("¿Cmo optimizo riego?", "irrigation_advice"), ("¿Q hago riego?", "irrigation_advice"),
    ("¿Mejor riego?", "irrigation_advice"), ("¿Cmo regar eficiente?", "irrigation_advice"),
    ("¿Cmo regar con poca agua?", "irrigation_advice"),
    ("¿Q sistema riego?", "irrigation_advice"), ("¿Riego hoy?", "irrigation_advice"),
    ("¿Buen momento regar Bogotá?", "irrigation_advice"), ("¿Q regar Bogotá?", "irrigation_advice"),
    ("¿Riego adecuado Bogotá?", "irrigation_advice"),
    ("¿Buen momento regar Medellín?", "irrigation_advice"), ("¿Q regar Medellín?", "irrigation_advice"),
    ("¿Riego adecuado Medellín?", "irrigation_advice"),
    ("¿Buen momento regar Cali?", "irrigation_advice"), ("¿Q regar Cali?", "irrigation_advice"),
    ("¿Riego adecuado Cali?", "irrigation_advice"),
    ("¿Siembro tomate en secano sirve?", "irrigation_advice"),
    ("¿Conviene sembrar arroz si sólo tengo riego por goteo?", "irrigation_advice"),
    
    # Intenciones para preguntas dinámicas basadas en datasets
    ("¿Dónde es menos favorable maíz?", "least_favorable_department"),
    ("¿Qué departamento menos maíz?", "least_favorable_department"),
    ("¿Menos favorable sembrar maíz?", "least_favorable_department"),
    ("¿Dónde no sembrar maíz?", "least_favorable_department"),
    ("¿Dónde es menos favorable papa?", "least_favorable_department"),
    ("¿Qué departamento menos papa?", "least_favorable_department"),
    ("¿Menos favorable sembrar café?", "least_favorable_department"),
    ("¿Dónde no sembrar café?", "least_favorable_department"),
    ("¿Dónde es menos favorable tomate?", "least_favorable_department"),
    ("¿Qué departamento menos tomate?", "least_favorable_department"),
    ("¿Menos favorable sembrar arroz?", "least_favorable_department"),
    ("¿Dónde no sembrar arroz?", "least_favorable_department"),
]

if __name__ == "__main__":
    train_intent_model(training_data)